#!/usr/bin/env python3
"""Quantify sequence coherence of TPIA2 gene-ID conversion rows.

The input FASTA table is generated by `fetch_tpia_crosswalk_sequences.py`.
For each Yunkang10 source row, CDS sequences from YK10, SCZ v1 and SCZ v2
are globally aligned. We report identity over nongap aligned positions and
full-alignment identity separately so truncated gene models remain visible.

Within-family paralog comparisons are also reported for the two FLS and two
LAR source rows. These metrics test sequence provenance and paralog separation;
they do not prove one-to-one orthology across species.
"""
from __future__ import annotations
import argparse,csv,itertools
from pathlib import Path
from Bio import Align

GENOMES=['yk10','sczv1','sczv2']
ID_COL={'yk10':'yk10','sczv1':'sczv1','sczv2':'sczv2'}
PARALOG_PAIRS=[('FLS','CSA006950','CSA008358'),('LAR','CSA018523','CSA019984')]

def align_metrics(a:str,b:str,aligner:Align.PairwiseAligner):
    al=aligner.align(a,b)[0];c=al.counts()
    nongap=c.identities+c.mismatches;full=nongap+c.gaps
    return {
        'nongap_identity':c.identities/nongap if nongap else 0.0,
        'full_alignment_identity':c.identities/full if full else 0.0,
        'gap_columns':c.gaps,
    }

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--crosswalk',type=Path,required=True);ap.add_argument('--fasta-records',type=Path,required=True);ap.add_argument('--row-output',type=Path,required=True);ap.add_argument('--paralog-output',type=Path,required=True);a=ap.parse_args()
    with a.crosswalk.open(newline='',encoding='utf-8') as f:cross=[r for r in csv.DictReader(f) if r['crosswalk_status']=='TPIA2_gene_id_convert_exact_row']
    with a.fasta_records.open(newline='',encoding='utf-8') as f:fr=list(csv.DictReader(f))
    seq={}
    for r in fr:
        if r['sequence_type']!='cds':continue
        gid=r['header'].split('\t')[0].strip()
        seq[(r['crosswalk_column'],gid)]=r['sequence'].strip().upper()
    aligner=Align.PairwiseAligner();aligner.mode='global';aligner.match_score=1;aligner.mismatch_score=0;aligner.open_gap_score=-1;aligner.extend_gap_score=-0.1
    out=[]
    for r in cross:
        ids={g:r[ID_COL[g]].split('.')[0] for g in GENOMES}
        ss={g:seq[(g,ids[g])] for g in GENOMES}
        pairvals=[]
        pairtext=[]
        for g1,g2 in itertools.combinations(GENOMES,2):
            m=align_metrics(ss[g1],ss[g2],aligner);pairvals.append(m)
            pairtext.append(f"{g1}-{g2}:nongap={m['nongap_identity']:.6f};full={m['full_alignment_identity']:.6f};gaps={m['gap_columns']}")
        lengths={g:len(ss[g]) for g in GENOMES}
        out.append({
            'source_id':r['source_id'],'source_feature':r['source_feature'],
            'yk10_id':r['yk10'],'sczv1_id':r['sczv1'],'sczv2_id':r['sczv2'],
            'yk10_cds_bp':lengths['yk10'],'sczv1_cds_bp':lengths['sczv1'],'sczv2_cds_bp':lengths['sczv2'],
            'min_pairwise_nongap_identity':f"{min(x['nongap_identity'] for x in pairvals):.6f}",
            'min_pairwise_full_alignment_identity':f"{min(x['full_alignment_identity'] for x in pairvals):.6f}",
            'min_to_max_cds_length_ratio':f"{min(lengths.values())/max(lengths.values()):.6f}",
            'pairwise_metrics':' | '.join(pairtext),
            'sequence_provenance_decision':'crosswalk row sequence-supported over overlapping CDS; retain gene-model length differences explicitly',
            'claim_boundary':'high overlapping-sequence identity supports TPIA row correspondence but does not force complete one-to-one gene-model orthology'
        })
    # Map source ID -> genome sequence for paralog pairs.
    bysrc={r['source_id']:r for r in cross};par=[]
    for feature,s1,s2 in PARALOG_PAIRS:
        for g in GENOMES:
            r1,r2=bysrc[s1],bysrc[s2];i1=r1[ID_COL[g]].split('.')[0];i2=r2[ID_COL[g]].split('.')[0]
            q=align_metrics(seq[(g,i1)],seq[(g,i2)],aligner)
            par.append({
                'feature':feature,'genome':g,'source_id_1':s1,'source_id_2':s2,
                'genome_id_1':r1[ID_COL[g]],'genome_id_2':r2[ID_COL[g]],
                'cds_bp_1':len(seq[(g,i1)]),'cds_bp_2':len(seq[(g,i2)]),
                'nongap_identity':f"{q['nongap_identity']:.6f}",'full_alignment_identity':f"{q['full_alignment_identity']:.6f}",'gap_columns':q['gap_columns'],
                'interpretation':'distinct paralog/source rows; do not collapse by enzyme-family symbol',
                'claim_boundary':'pairwise sequence divergence demonstrates distinct source rows, not their deeper duplication age or functional equivalence'
            })
    for path,data in [(a.row_output,out),(a.paralog_output,par)]:
        path.parent.mkdir(parents=True,exist_ok=True)
        with path.open('w',newline='',encoding='utf-8') as f:
            w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader();w.writerows(data)
if __name__=='__main__':main()
